### ISSUE TITLE
PyRadio installation broken after upgrade to Ubuntu 23.04

### ISSUE THREAD

**Issue by sqvist** [coderholic/pyradio#190] opened 2023-04-19 07:51 UTC
I upgraded my PC to Ubuntu 23.04, and later then tried to start my "pyradio". 
I was met with an error that "Module not found: Pyradio". 

Tried to reinstall pyradio, but the OS didnt let me install pip-packages unless I used a virtual environment OR tried searching for the package on apt repository (like apt search python3-pyradio). Such were not to be found ofcourse. 

I then fired up a venv as suggested, downloaded the "install.py" script and tried to run it with .<my venv>/bin/python3 install.py, which worked good until (probably) it extracted its content in /tmp-folder (and therefore being outside of the .venv) . Ubuntu didnt like that for some reason.

What finally got me back running again were to follow the steps for building manually, as found here:
https://github.com/coderholic/pyradio/issues/104#issuecomment-656113840

Suggestion: Maybe make a parameter to use "current dir" as install-location and not /tmp ? 
Maybe find a better way around this than i did? :) 

Otherwise, thanks for a good radio-client! Much appreciate it!

**Comment by s-n-g** [comment] 2023-04-19 12:56
I have just installed ubuntu 23.04 in a vm and I can confirm the issue :wink:

Debian suggests that `pipx` (from debian repos) should be used in this situation.

For `pyradio` that would mean to change the installation scripts to support it.

There is a workaround though, exporting `PIP_BREAK_SYSTEM_PACKAGES=1` before running `python3 install.py`, but I would not recommend it, since it would make it practically impossible to automatically update `pyradio`.

So, I will be looking into the first solution.

**Comment by stefans-sli** [comment] 2023-04-19 13:41
Yes, some suggestions i found were also to send "--break-system-packages" .  But it didnt feel right. Maybe using .venv is not a bad idea, but the install-script doesnt allow it at the moment. 

Good thing that you experienced the same issue. Makes developing much easier :)

**Comment by s-n-g** [comment] 2023-04-19 14:54
I have successfully used

```
export PIP_BREAK_SYSTEM_PACKAGES=1
python3 install.py
```

and it's all right regarding system stability; `pyraio` already installs locally only.

So, I would be perfectly happy with such a solution.

But then, in order to update it from withing `pyradio`, it would require the `PIP_BREAK_SYSTEM_PACKAGES` variable to be somehow defined... so, no go :(

**Comment by s-n-g** [comment] 2023-04-20 09:15
> That might work, but seems like a "quick fix" more than a stable installation. :)

Well, that's a matter of opinion :)
For me, as long as the application does not interfear with distro python packages, it is a safe and viable solution.

> How well does an install & upgrade go if the install-script uses the current directory (like ".venv/pyradio/") and not /tmp ?
> Because you can probably get away if using a virtual environment. It doesn't seem to bother about SYSTEM_PACKAGES there.

Using `/tmp` is not the problem here.
Using a `.venv/pyradio/` directory (or a virtual environment, for that matter) introduces new problems: links to executables, etc, which `pipx` tries to handle.

> Or if you could use "apt install" for python3-packages and pipx for pyradio?
> I dont know really, im brainstorming :)

Yes, one could `sudo apt install pipx` (if that's what you mean), but then again there are other issues as well.

`pyradio` uses `python3 isntall.py` to perform the installation, install docs, a desktop file, data files, etc.
To do that, it needs distro python packages, at least `wheel`, `requests` and `rich`.

Then after a **pipx installation** these packages have to be installed in the **pyradio pipx virtual environment** as well.

I don't know, I need to do some testing in ubuntu :wink:

**Comment by sqvist** [comment] 2023-04-20 09:57
You do so! I am new on the python language so i do not know the best way. I figure you find a way eventually :).

**Comment by s-n-g** [comment] 2023-05-01 18:47
Hi @sqvist 

I have put something together, but I need your help to test it.

If you are up to it
1. uninstall `pyradio` 
2. download `install.py` from [here](https://raw.githubusercontent.com/s-n-g/pyradio/devel/pyradio/install.py) or execute 
```
cd
rm install.py 2>/dev/null
wget https://raw.githubusercontent.com/s-n-g/pyradio/devel/pyradio/install.py
```
3. read https://github.com/s-n-g/pyradio/blob/devel/linux-pipx.md
4. follow the instructions in the previous link
5. install `pyradio` using one of the following commands:

System dependent installation
```
cd
python3 install.py --sng-devel
```

Fully isolated installation
```
cd
python3 install.py --sng-devel -i
```

It has worked on my Ubuntu 23.04 vm.
I hope it works without a problem on a real system too!

**Comment by sqvist** [comment] 2023-05-02 08:40
hi  @s-n-g !
Absolutely !

This is the result of the "-i" installation:
`Installing PyRadio...
Using directory: "/home/stefan/.config/pyradio/data/.cache"
Old "/home/stefan/.config/pyradio/data/.cache" found. Deleting...
Downloading PyRadio source code...
  url: "https://github.com/s-n-g/pyradio/archive/devel.zip"
  filename: "/home/stefan/.config/pyradio/data/.cache/pyradio-devel.zip"
Extracting RyRadio source code...
Traceback (most recent call last):
  File "/home/stefan/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 819, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/install.py", line 30, in install
    package_name = package_name_from_spec(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/commands/common.py", line 333, in package_name_from_spec
    package_name = venv.install_package_no_deps(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 268, in install_package_no_deps
    old_package_set = self.list_installed_packages()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pipx/venv.py", line 348, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The installation has failed!!!
Please report this at https://github.com/coderholic/pyradio/issues`

The same error occurs on the "system dependent installation".

My pipx version is:
`> pipx --version
1.1.0`

**Comment by s-n-g** [comment] 2023-05-02 09:51
ok, that's not good...
Maybe something got wrong from a previous attempt...

Can you please try
```
rm -rf ~/.local/pipx
```

and then try the installation again?


This is what i get on Ubuntu 23.04

https://user-images.githubusercontent.com/5807638/235635201-1f9fa2fe-7729-4bfe-9b8b-d4f300efad09.mp4

**Comment by sqvist** [comment] 2023-05-02 10:28
Yes, that made the trick! 
I thought i had a rather clean install of pyradio and dependencies. But not...

I couldnt "uninstall pyradio" as you asked earlier, since i couldnt run "pyradio -R" . So maybe i couldnt remove it completely .

**Comment by s-n-g** [comment] 2023-05-02 10:45
> Yes, that made the trick!
> I thought i had a rather clean install of pyradio and dependencies. But not...

Wonderful!
I can go no now and finish the new installation script!


> I couldnt "uninstall pyradio" as you asked earlier, since i couldnt run "pyradio -R" . So maybe i couldnt remove it completely .

Yeah, it was half working...

I will keep this one open until I release 0.9.2.6 officially.
Then I will post again and help you install the official one and close the issue.

**Comment by s-n-g** [comment] 2023-05-08 11:38
Hi @sqvist 

I have just released **PyRadio 0.9.2.6**

Since you will not get an update notification for this one, you should

```
cd
rm install.py 2>/dev/null
wget https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py
```

and then

```
python3 install.py
```
or 

```
python3 install.py -i
```

**Comment by sqvist** [comment] 2023-05-08 13:10
Hello @s-n-g 
Congratulations on the release!
I just ran your installscript and it went flawless. It suggested me removing some old python3.10 stuff, which I did. 
It works still. 
Good job!

**Comment by s-n-g** [comment] 2023-05-08 13:18
Wonderful!
Thank you very much for reporting this one, and your patience testing things and all

**Closed by s-n-g** 2023-05-08 13:18 UTC
