### ISSUE TITLE
[BUG] Appending a radio station with `A` in a playlist leads to a crash.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#222] opened 2024-01-05 10:34 UTC
**Describe the bug**

I pressed `A` in a playlist and added a radio station. Then, I saw crash.

```
Reading playlist...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/pyradio", line 8, in <module>
    sys.exit(shell())
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyradio/main.py", line 876, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.11/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyradio/radio.py", line 978, in setup
    self.run()
  File "/usr/lib/python3.11/site-packages/pyradio/radio.py", line 1835, in run
    ret = self.keypress(c)
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pyradio/radio.py", line 7796, in keypress
    self.refreshBody()
  File "/usr/lib/python3.11/site-packages/pyradio/radio.py", line 1247, in refreshBody
    self._redisplay[self._redisplay_list[n][0]]()
  File "/usr/lib/python3.11/site-packages/pyradio/radio.py", line 10213, in _redisplay_stations_and_playlists
    self.__displayBodyLine(lineNum, pad, self.stations[i])
                                         ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**System (please complete the following information):**
 - OS: Gentoo Linux
 - **Python** version: 3.11.7
 - **PyRadio** Version: 0.9.2.20

**Comment by s-n-g** [comment] 2024-01-05 12:46
I cannot reproduce...
Pressing `A` works ok here


https://github.com/coderholic/pyradio/assets/5807638/6471bc88-b0ad-4fbe-9c03-3616e23c2779

Can you please post the actual playlist you are trying to append the station to?

**Comment by s-n-g** [comment] 2024-01-05 13:22
ok, I got it

Created a new playlist, added one station, all ok
Tried to add a new station and got the crash

On it!

**Comment by s-n-g** [comment] 2024-01-05 15:14
Fixed in https://github.com/coderholic/pyradio/releases/tag/0.9.2.22

**Closed by s-n-g** 2024-01-05 15:14 UTC
